# Generated by Django 4.2.4 on 2023-08-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
