# Generated by Django 4.2.4 on 2023-08-10 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comment_created_at_news_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
